name: 'poetry-setup'
description: 'composite action to setup poetry'
inputs:
  python_version:  # id of input
    description: 'version of python'
    required: true
    default: '3.7'
runs:
  using: "composite"
  steps:
    - name: get repo
      uses: actions/checkout@v2
    - run: echo "Prepare Setup"
      shell: bash
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install poetry
      uses: snok/install-poetry@v1.0.0
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

